[package]
name = "canary"
version = "0.2.4"
edition = "2021"

repository = "https://github.com/znx3p0/canary"
keywords = [ "rpc", "async", "network", "microservices", "api" ]
description = "provides ergonomic abstractions for network communication and more"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
futures = "0.3.21"

# serde
serde = { version = "1.0.136", features = [ "derive" ] }
serde_repr = "0.1.7"

# formats
bincode = { version = "1.3.3" }
serde_json = { version = "1.0.79", optional = true}
bson = { version = "2.1.0", optional = true}
postcard = { version = "0.7.3", features = [ "alloc" ], optional = true }

# static serde
bytes = { version = "1.1.0", optional = true }
smallvec = { version = "1.8.0", features = [ "write" ], optional = true }
impl-trait-for-tuples = { version = "0.2.2", optional = true }

# encryption
snow = "0.9.0" # api may change
rand = "0.8.5"

tracing = "0.1.32"
cfg-if = "1.0.0"
compact_str = { version = "0.3.1", features = [ "serde" ] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.17.0", features = [ "net", "io-util", "time" ] }

# websocket support
async-tungstenite = { version = "0.17.2", features = [ "tokio-runtime" ] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
reqwasm = { version = "0.5.0" }
getrandom = { version = "~0.2.5", features = [ "js" ] }
uuid = { version = "~0.8.2", features = [ "wasm-bindgen" ] }
async-timer = "0.7.4"

[features]
json_ser = [ "serde_json" ]
bson_ser = [ "bson" ]
postcard_ser = [ "postcard" ]

static_ser = [ "bytes", "smallvec", "impl-trait-for-tuples" ]
